name: Ecki Bear
favicon: null
layout_spectrum: 0.11657
typography_spectrum: 0.32077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#8e8181'
    - '#a59595'
    - '#444040'
    - '#595252'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
