name: Ecki Bear
favicon: null
layout_spectrum: 0.1743695114273578
typography_spectrum: 0.3785656876862049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3895838363096118
  lightness: 0.7573333010077477
  saturation: 0.6940754672978073
  rhythmicContrast: 0.7929081704933196
purpose: []
