typography_spectrum: 0.3992527239024639
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.4255090639926493
  lightness: 0.993696250487119
  saturation: 0.2190452718641609
  rhythmicContrast: 0.5630841194652021
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.059031223179772496
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: I like it. What is it?
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ECKI BEAR
purpose: []
