typography_spectrum: 0.59203
color:
  brandColors:
    - '#ffffff'
    - '#cc9700'
    - '#bfbf00'
    - '#ffff00'
    - '#f5e168'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90987
analytics:
  google: null
  facebook: null
  twitter: null
logo: null
name: ECKI BEAR
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ECKI BEAR
purpose: []
