name: Ecki Bear
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17498
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Ecki Bear
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#8e8181'
    - '#a59595'
    - '#444040'
    - '#595252'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
